/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hangman;

// kütüphaneler
import java.io.File;
import java.util.*;
import javax.sound.sampled.*;
import javax.swing.*;

class Kontrol{
    public static String secilen;
    public static int yanlis = 0;
    public static String acilacakHarf;
    public static int cikanHarf=0;
    public static int cikacakHarf;
    public static Random random = new Random();
    public static boolean harfYok=true;
    public static Clip clip;
}
class KolayKelime{
    
    
    public static ArrayList<String> kolayKelimeler = new ArrayList<String>();
    public static String kolayKelimelerA[] = 
    {
        "pijama","gömlek","balina","leylek","bülbül","maymun","timsah","kaleci","yastık","cüzdan","cetvel","musluk",
        "gözlük","defter","poster","bardak","çarşaf","muhtar","dürbün","mermer"
    };
    
}
class OrtaKelime{
    public static ArrayList<String> ortaKelimeler = new ArrayList<String>();
    public static String ortaKelimelerA[] = 
    {
        "testere","tencere","mobilya","karyola","telefon","karınca","papağan","örümcek","penguen","makarna","domates",
        "ıspanak","patates","şeftali","öğrenci","klarnet","darbuka","bakteri","çekmece","bisküvi"
    };
}
class ZorKelime{
    public static  ArrayList<String> zorKelimeler = new ArrayList<String>();
    public static String zorKelimelerA[] = 
    {
        "aforizma","arkeolog","atmosfer","bergamot","biyoloji","jeofizik","komposto","kategori","karambol",
        "dedikodu","depozito","difüzyon","dokuzgen","dondurma","marangoz","nostalji","romantik","semizotu",
        "milyoner","diksiyon"
    };
}
public class anaoyun extends javax.swing.JFrame {
    // resimler
    
    ImageIcon arkaplan = new ImageIcon("defter.png");
    ImageIcon daragaci = new ImageIcon("daragaci.png");
    ImageIcon head = new ImageIcon("head.png");    
    ImageIcon chest = new ImageIcon("chest.png");
    ImageIcon legs = new ImageIcon("legs.png");
    ImageIcon leftarm = new ImageIcon("leftarm.png");
    ImageIcon rightarm = new ImageIcon("rightarm.png");
    ImageIcon sondua = new ImageIcon("sondua.png");
    ImageIcon tanrininlutfu = new ImageIcon("tanrininlutfu.png");
   
   
    // listeler
    ArrayList<JLabel> harfler = new ArrayList<>();
   
   ArrayList<String> kullanilanHarfler = new ArrayList<String>();
    
    
     
     void HerseyiSifirla(){
         kafaResmi.setVisible(false);
        gogusResmi.setVisible(false);
        bacakResmi.setVisible(false);
        sagkolResmi.setVisible(false);
        solkolResmi.setVisible(false);
        Kontrol.cikanHarf = 0;
        Kontrol.yanlis = 0;
        Kontrol.acilacakHarf="";
        for(JLabel q : harfler) q.setText("_");
        sonduaGosterilenHarf.setText("");
        sonduaResmi.setEnabled(true);
         tanrininlutfuResmi.setEnabled(true);
         kullanilanHarflerGosterme.setText("");
         harfGirme.setText("");
     }
    
    
    

    /**
     * Creates new form anaoyun
     */
    public anaoyun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        harfGirme = new javax.swing.JTextField();
        deneButonu = new javax.swing.JButton();
        tire1 = new javax.swing.JLabel();
        tire2 = new javax.swing.JLabel();
        tire3 = new javax.swing.JLabel();
        tire4 = new javax.swing.JLabel();
        tire5 = new javax.swing.JLabel();
        tire6 = new javax.swing.JLabel();
        tire7 = new javax.swing.JLabel();
        tire8 = new javax.swing.JLabel();
        kolayButonu = new javax.swing.JButton();
        ortaButonu = new javax.swing.JButton();
        zorButonu = new javax.swing.JButton();
        kullanilanHarflerLabel = new javax.swing.JLabel();
        kullanilanHarflerGosterme = new javax.swing.JLabel();
        bacakResmi = new javax.swing.JLabel();
        kafaResmi = new javax.swing.JLabel();
        gogusResmi = new javax.swing.JLabel();
        sagkolResmi = new javax.swing.JLabel();
        solkolResmi = new javax.swing.JLabel();
        daragaciResmi = new javax.swing.JLabel();
        tanrininlutfuResmi = new javax.swing.JLabel();
        sonduaResmi = new javax.swing.JLabel();
        sonduaGosterilenHarf = new javax.swing.JLabel();
        kelimeSecmeYazisi = new javax.swing.JLabel();
        arkaplanResmi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        harfGirme.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        getContentPane().add(harfGirme);
        harfGirme.setBounds(470, 240, 45, 43);

        deneButonu.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        deneButonu.setText("Try");
        deneButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deneButonuActionPerformed(evt);
            }
        });
        getContentPane().add(deneButonu);
        deneButonu.setBounds(520, 240, 100, 43);

        tire1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        tire1.setText("_");
        getContentPane().add(tire1);
        tire1.setBounds(330, 130, 50, 67);

        tire2.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        tire2.setText("_");
        getContentPane().add(tire2);
        tire2.setBounds(390, 130, 50, 67);

        tire3.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        tire3.setText("_");
        getContentPane().add(tire3);
        tire3.setBounds(450, 130, 50, 67);

        tire4.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        tire4.setText("_");
        getContentPane().add(tire4);
        tire4.setBounds(510, 130, 50, 67);

        tire5.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        tire5.setText("_");
        getContentPane().add(tire5);
        tire5.setBounds(570, 130, 50, 67);

        tire6.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        tire6.setText("_");
        getContentPane().add(tire6);
        tire6.setBounds(630, 130, 50, 67);

        tire7.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        tire7.setText("_");
        getContentPane().add(tire7);
        tire7.setBounds(690, 130, 50, 67);

        tire8.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        tire8.setText("_");
        getContentPane().add(tire8);
        tire8.setBounds(750, 130, 50, 67);

        kolayButonu.setBackground(new java.awt.Color(51, 255, 0));
        kolayButonu.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        kolayButonu.setText("Easy");
        kolayButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolayButonuActionPerformed(evt);
            }
        });
        getContentPane().add(kolayButonu);
        kolayButonu.setBounds(10, 520, 90, 32);

        ortaButonu.setBackground(new java.awt.Color(255, 204, 0));
        ortaButonu.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        ortaButonu.setText("Medium");
        ortaButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ortaButonuActionPerformed(evt);
            }
        });
        getContentPane().add(ortaButonu);
        ortaButonu.setBounds(110, 520, 110, 32);

        zorButonu.setBackground(new java.awt.Color(255, 0, 0));
        zorButonu.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        zorButonu.setText("Hard");
        zorButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zorButonuActionPerformed(evt);
            }
        });
        getContentPane().add(zorButonu);
        zorButonu.setBounds(230, 520, 90, 32);

        kullanilanHarflerLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        kullanilanHarflerLabel.setText("Used letters:");
        getContentPane().add(kullanilanHarflerLabel);
        kullanilanHarflerLabel.setBounds(10, 480, 176, 26);

        kullanilanHarflerGosterme.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(kullanilanHarflerGosterme);
        kullanilanHarflerGosterme.setBounds(180, 480, 630, 30);
        getContentPane().add(bacakResmi);
        bacakResmi.setBounds(150, 310, 100, 120);
        getContentPane().add(kafaResmi);
        kafaResmi.setBounds(170, 160, 60, 60);
        getContentPane().add(gogusResmi);
        gogusResmi.setBounds(180, 210, 50, 120);
        getContentPane().add(sagkolResmi);
        sagkolResmi.setBounds(220, 130, 50, 120);
        getContentPane().add(solkolResmi);
        solkolResmi.setBounds(160, 130, 40, 120);
        getContentPane().add(daragaciResmi);
        daragaciResmi.setBounds(10, 50, 260, 400);

        tanrininlutfuResmi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tanrininlutfuResmi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanrininlutfuResmiMouseClicked(evt);
            }
        });
        getContentPane().add(tanrininlutfuResmi);
        tanrininlutfuResmi.setBounds(600, 350, 80, 130);

        sonduaResmi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sonduaResmi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sonduaResmiMouseClicked(evt);
            }
        });
        getContentPane().add(sonduaResmi);
        sonduaResmi.setBounds(500, 350, 80, 130);

        sonduaGosterilenHarf.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        getContentPane().add(sonduaGosterilenHarf);
        sonduaGosterilenHarf.setBounds(520, 500, 50, 40);

        kelimeSecmeYazisi.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        kelimeSecmeYazisi.setText("Select a level for new word.");
        getContentPane().add(kelimeSecmeYazisi);
        kelimeSecmeYazisi.setBounds(10, 460, 270, 21);
        getContentPane().add(arkaplanResmi);
        arkaplanResmi.setBounds(0, 0, 820, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       // oyun acildiginda gerekli ayarlar burda yapiliyor
        kafaResmi.setIcon(head);
       gogusResmi.setIcon(chest);
       bacakResmi.setIcon(legs);
        daragaciResmi.setIcon(daragaci);
        sagkolResmi.setIcon(rightarm);
        solkolResmi.setIcon(leftarm);
        arkaplanResmi.setIcon(arkaplan);
        tanrininlutfuResmi.setIcon(tanrininlutfu);
        sonduaResmi.setIcon(sondua);
       this.setSize(820,590);
        tire7.setVisible(false);
       tire8.setVisible(false);
        for (String x : KolayKelime.kolayKelimelerA){
            KolayKelime.kolayKelimeler.add(x);//pratiklik açısından diziyi 
            //listeye aktarıp listeyi kullanıyorum.
        }
        for (String y : OrtaKelime.ortaKelimelerA){
            OrtaKelime.ortaKelimeler.add(y);
        }
        for (String z : ZorKelime.zorKelimelerA){
            ZorKelime.zorKelimeler.add(z);
        }
        //Bütün tireleri harfler adlı bir listede tutuluyor
        harfler.add(tire1);
        harfler.add(tire2);
        harfler.add(tire3);
        harfler.add(tire4);
        harfler.add(tire5);
        harfler.add(tire6);
        harfler.add(tire7);
        harfler.add(tire8);
    }//GEN-LAST:event_formWindowOpened

    private void kolayButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolayButonuActionPerformed
        // kolay butonu
        HerseyiSifirla();
        tire7.setVisible(false);
       tire8.setVisible(false);
        Kontrol.secilen = KolayKelime.kolayKelimeler.get(Kontrol.random.nextInt(KolayKelime.kolayKelimeler.size()));
        Kontrol.cikacakHarf = 6;
       
    }//GEN-LAST:event_kolayButonuActionPerformed

    private void deneButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deneButonuActionPerformed
        // dene butonu
        Kontrol.acilacakHarf = (harfGirme.getText()).toLowerCase();
        Kontrol.harfYok=true;
        for(int i = 0;i<Kontrol.cikacakHarf;i++){
              
            if(Kontrol.acilacakHarf.equals(Character.toString(Kontrol.secilen.charAt(i))) ) {
                harfler.get(i).setText(Kontrol.acilacakHarf.toUpperCase());
                Kontrol.cikanHarf++;
                Kontrol.harfYok = false;
               
                if(Kontrol.cikacakHarf==Kontrol.cikanHarf){
                    KolayKelime.kolayKelimeler.remove(Kontrol.secilen);
                    OrtaKelime.ortaKelimeler.remove(Kontrol.secilen);
                    ZorKelime.zorKelimeler.remove(Kontrol.secilen);
                    for(JLabel q : harfler) q.setText("_");
                    kullanilanHarflerGosterme.setText("");
                    try {
                File wavFile = new File("sounds\\correct.wav");
                Kontrol.clip = AudioSystem.getClip();
                Kontrol.clip.open(AudioSystem.getAudioInputStream(wavFile));
                Kontrol.clip.start();
            } catch (Exception e) {
                System.out.println(e);
            }
                    Kontrol.acilacakHarf="";
                    JOptionPane.showMessageDialog(null, "Bildiniz! Yeni Kelime için Seviye Seçebilirsniz.");
                }
                
            }
              
            }
                    
        if(Kontrol.harfYok)Kontrol.yanlis++;
                switch(Kontrol.yanlis){
                    case 1:
                        kafaResmi.setVisible(true);
                        
                        break;
                    case 2:
                        gogusResmi.setVisible(true);
                        
                        break;
                    case 3:
                        sagkolResmi.setVisible(true);
                        
                        break;
                    case 4:
                        solkolResmi.setVisible(true);
                        
                        break;
                    case 5:
                        bacakResmi.setVisible(true);
                        try {
                            File wavFile = new File("sounds\\wrong.wav");
                            Kontrol.clip = AudioSystem.getClip();
                            Kontrol.clip.open(AudioSystem.getAudioInputStream(wavFile));
                            Kontrol.clip.start();
                            } catch (Exception e) {
                                 System.out.println(e);
                            }
                        JOptionPane.showMessageDialog(null, "Adamı kurtaramadınız! Kelime : "+ Kontrol.secilen);
                        
                        KolayKelime.kolayKelimeler.remove(Kontrol.secilen);
                        OrtaKelime.ortaKelimeler.remove(Kontrol.secilen);
                        ZorKelime.zorKelimeler.remove(Kontrol.secilen);
                        Kontrol.secilen = "";
                        for(JLabel q : harfler) q.setText("_");
                        kullanilanHarflerGosterme.setText("");
                        Kontrol.acilacakHarf="";
                        break;
                }
        
        kullanilanHarflerGosterme.setText(kullanilanHarflerGosterme.getText()+Kontrol.acilacakHarf);
        harfGirme.setText("");
    }//GEN-LAST:event_deneButonuActionPerformed

    private void ortaButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ortaButonuActionPerformed
        // orta seviye butonu
        HerseyiSifirla();
        tire7.setVisible(true);
        tire8.setVisible(false);
        Kontrol.secilen = OrtaKelime.ortaKelimeler.get(Kontrol.random.nextInt(OrtaKelime.ortaKelimeler.size()));
       Kontrol.cikacakHarf = 7;
       
    }//GEN-LAST:event_ortaButonuActionPerformed

    private void zorButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zorButonuActionPerformed
        // zor seviye butonu
        HerseyiSifirla();
        tire7.setVisible(true);
       tire8.setVisible(true);
       Kontrol.secilen = ZorKelime.zorKelimeler.get(Kontrol.random.nextInt(ZorKelime.zorKelimeler.size()));
       Kontrol.cikacakHarf = 8;
       
    }//GEN-LAST:event_zorButonuActionPerformed

    private void sonduaResmiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sonduaResmiMouseClicked
       // son dua kartı
        if(sonduaResmi.isEnabled()){
            try {
                File wavFile = new File("sounds\\sondua.wav");
                Kontrol.clip = AudioSystem.getClip();
                Kontrol.clip.open(AudioSystem.getAudioInputStream(wavFile));
                Kontrol.clip.start();
            } catch (Exception e) {
                System.out.println(e);
            }    
        sonduaGosterilenHarf.setText(Character.toString(Kontrol.secilen.charAt(Kontrol.random.nextInt(Kontrol.secilen.length()))));
            sonduaResmi.setEnabled(false);
        }
        else{
            evt.consume();
        }
    }//GEN-LAST:event_sonduaResmiMouseClicked

    private void tanrininlutfuResmiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanrininlutfuResmiMouseClicked
        // tanrinin lutfu karti
        if(tanrininlutfuResmi.isEnabled()){
        if(Kontrol.yanlis>0){
            try {
                File wavFile = new File("sounds\\tanrininlutfu.wav");
                Kontrol.clip = AudioSystem.getClip();
                Kontrol.clip.open(AudioSystem.getAudioInputStream(wavFile));
                Kontrol.clip.start();
            } catch (Exception e) {
                System.out.println(e);
            }}
        if(bacakResmi.isVisible()){
            bacakResmi.setVisible(false);
            tanrininlutfuResmi.setEnabled(false);
            Kontrol.yanlis--;
        }else if(sagkolResmi.isVisible()){
            sagkolResmi.setVisible(false);
            tanrininlutfuResmi.setEnabled(false);
            Kontrol.yanlis--;
        }else if(solkolResmi.isVisible()){
            solkolResmi.setVisible(false);
            tanrininlutfuResmi.setEnabled(false);
            Kontrol.yanlis--;
        }else if(gogusResmi.isVisible()){
            gogusResmi.setVisible(false);
            tanrininlutfuResmi.setEnabled(false);
            Kontrol.yanlis--;
        }else if(kafaResmi.isVisible()){
            kafaResmi.setVisible(false);
            tanrininlutfuResmi.setEnabled(false);
            Kontrol.yanlis--;
        }else{
            JOptionPane.showMessageDialog(null,"Kullanamazsınız, önce hata yapın!");
        }
        }
        else{
            evt.consume();
        }
    }//GEN-LAST:event_tanrininlutfuResmiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anaoyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anaoyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anaoyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anaoyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anaoyun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arkaplanResmi;
    private javax.swing.JLabel bacakResmi;
    private javax.swing.JLabel daragaciResmi;
    private javax.swing.JButton deneButonu;
    private javax.swing.JLabel gogusResmi;
    private javax.swing.JTextField harfGirme;
    private javax.swing.JLabel kafaResmi;
    private javax.swing.JLabel kelimeSecmeYazisi;
    private javax.swing.JButton kolayButonu;
    private javax.swing.JLabel kullanilanHarflerGosterme;
    private javax.swing.JLabel kullanilanHarflerLabel;
    private javax.swing.JButton ortaButonu;
    private javax.swing.JLabel sagkolResmi;
    private javax.swing.JLabel solkolResmi;
    private javax.swing.JLabel sonduaGosterilenHarf;
    private javax.swing.JLabel sonduaResmi;
    private javax.swing.JLabel tanrininlutfuResmi;
    private javax.swing.JLabel tire1;
    private javax.swing.JLabel tire2;
    private javax.swing.JLabel tire3;
    private javax.swing.JLabel tire4;
    private javax.swing.JLabel tire5;
    private javax.swing.JLabel tire6;
    private javax.swing.JLabel tire7;
    private javax.swing.JLabel tire8;
    private javax.swing.JButton zorButonu;
    // End of variables declaration//GEN-END:variables
}
